apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zivgke-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - zivgke.26333222.xyz
      secretName: zivgke-tls
  rules:
    - host: zivgke.26333222.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nest-service
                port:
                  number: 80
